[package]
name = "stand_up"
version = "0.1.0"
authors = ["Angeline Mulet-Marquis <angelinemm@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9"
config = "0.9.2"
chrono = "0.4.6"
slack = "0.22.0"
assert_matches = "1.3.0"
actix-web="1.0.7"