version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.34.1
    steps:
      - checkout
      - run:
          name: Check formatting
          command: |
            rustup component add rustfmt
            cargo fmt --all -- --check
      - run:
          name: Check clippy
          command: |
            rustup component add clippy
            cargo clippy -- -D warnings
      - run:
          name: Cargo check
          command: |
            cargo check
      - run:
          name: Unittests
          command: |
            cargo test